# Generated by Django 4.0.6 on 2022-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_ratingstar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='description',
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
